# Generated by Django 3.2.4 on 2021-06-18 15:05

import books.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=books.utils.upload_collection_image)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(default=3)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='books.section')),
            ],
        ),
    ]
